site_name: 地球反菠萝姐组织
nav:
- 首页: MAIN.md
theme: 
   name: material
   custom_dir: docs/overrides
   language: zh
   # logo: 
   # favicon: 
   icon:
        repo: fontawesome/brands/github
   features:
        - navigation.footer
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.expand
        - toc.follow
        - navigation.top
        - content.code.annotate
        - announce.dismiss
        - navigation.indexes
        - navigation.expand
        - search.suggest
        - search.highlight
        - search.share
site_description: 消灭菠萝暴政，一起反对菠萝！
site_url: https://Your-Grandfather.github.io/
site_author: 地球反菠萝姐组织
copyright: ©2021-2023 
plugins:
    - search:
        lang:
            - en
            - ja
            - zh
        separator: '[\s\-\.]+'
    - git-revision-date-localized:
        enable_creation_date: true
        type: timeago
        locale: zh
    - glightbox

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    homepage: https://Your-Grandfather.github.io/

# repo_url: https://github.com/Your-Grandfather/Your-Grandfather.github.io/
# repo_name: Your-Grandfather/Your-Grandfather.github.io
# edit_uri: https://github.com/Your-Grandfather/Your-Grandfather.github.io/edit/main/docs/

markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - tables
    - footnotes
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - attr_list
    - md_in_html
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
